version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: fantacalcio_postgres
    environment:
      POSTGRES_DB: fantacalcio
      POSTGRES_USER: fantacalcio_user
      POSTGRES_PASSWORD: fantacalcio_password
    ports:
      - "5433:5432"  # Changed to avoid conflicts
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fantacalcio_user -d fantacalcio"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: fantacalcio_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
