"""Initial migration placeholder

Revision ID: 0001_initial
Revises:
Create Date: 2025-09-20
"""



# revision identifiers, used by Alembic.
revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # TODO: replace with autogenerated commands after running `alembic revision --autogenerate`
    pass


def downgrade() -> None:
    # TODO: implement downgrade if necessary
    pass
