version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: giocatori
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ..:/app:cached
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/giocatori
    depends_on:
      - db
    command: bash -c "./scripts/run_alembic.sh upgrade head && bash"

volumes:
  db_data:
