from typing import Protocol, List
from app.domain.models import Player, Team


class PlayerRepository(Protocol):
    def list_all(self) -> List[Player]: ...

    def get_by_id(self, player_id: int) -> Player: ...

    def save(self, player: Player) -> Player: ...


class TeamRepository(Protocol):
    def list_all(self) -> List[Team]: ...

    def get_by_id(self, team_id: int) -> Team: ...
