---
name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: |
            ${{ runner.os }}-pip-
            ${{ matrix.python-version }}-
            ${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install dev tools
        run: |
          pip install black flake8 pytest
          pip install pytest-cov

      - name: Lint (black check)
        run: |
          black --check .

      - name: Lint (flake8)
        run: |
          flake8 --max-line-length=120

      - name: Run tests with coverage
        run: |
          python -m pytest --maxfail=1 --disable-warnings -q --cov=.

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ matrix.python-version }}
          path: htmlcov || coverage.xml || .
